spring:
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  datasource.url: jdbc:postgresql://localhost:5432/postgres
